DROP TRIGGER IF EXISTS RemoveWaitlistAfterEnroll;
DROP TRIGGER IF EXISTS after_user_insert;

DROP PROCEDURE IF EXISTS EnrollStudent;
DROP PROCEDURE IF EXISTS DropStudent;
DROP PROCEDURE IF EXISTS GetCourseTableInformation;
DROP PROCEDURE IF EXISTS GetFirstWaitlistedStudent;
DROP PROCEDURE IF EXISTS GetCourseTableInformation;
DROP PROCEDURE IF EXISTS GetCoursesByStudentID;
DROP PROCEDURE IF EXISTS GetCoursesByInstructorID;
DROP PROCEDURE IF EXISTS GetWaitlistForStudentID;
DROP PROCEDURE IF EXISTS GetWaitlistForInstructorID;
DROP PROCEDURE IF EXISTS GetWaitlistForEveryone;

DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS Waitlist;
DROP TABLE IF EXISTS Sections;
DROP TABLE IF EXISTS Prerequisites;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Instructors;
DROP TABLE IF EXISTS Administrators;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Courses;
